aliases:
  # Edit this comment somehow in order to invalidate the CircleCI cache.
  # Since the contents of this file affect the cache key, editing only a
  # comment will invalidate the cache without changing the behavior.
  restore_cache_step: &restore_cache_step
    restore_cache:
      key:
        dotcache-cache-{{checksum ".circleci/config.yml" }}-{{ checksum
        "pnpm-lock.yaml" }}
  save_cache_step: &save_cache_step
    save_cache:
      key:
        dotcache-cache-{{checksum ".circleci/config.yml" }}-{{ checksum
        "pnpm-lock.yaml" }}
      paths:
        - ~/.pnpm-store
  install_dependencies_step: &install_dependencies_step
    run:
      name: install-dependencies
      command: pnpm install --frozen-lockfile

  unit_test: &unit_test
    steps:
      - run:
          name: Install pnpm
          command: |
            curl -L https://pnpm.js.org/pnpm.js | node - add --global pnpm
      - checkout
      - *restore_cache_step
      - *install_dependencies_step
      - *save_cache_step
      - run:
          name: build
          command: 'pnpm build'
      - run:
          name: tests
          command: 'pnpm test'
      - run:
          name: lint
          command: 'pnpm lint'

version: 2
jobs:
  node-v14:
    docker:
      - image: cimg/node:14.19
    <<: *unit_test
    resource_class: large
  node-v16:
    docker:
      - image: cimg/node:16.15
    <<: *unit_test
    resource_class: large
  node-v17:
    docker:
      - image: cimg/node:17.9
    <<: *unit_test
    resource_class: large
  deploy:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - *restore_cache_step
      - *install_dependencies_step
      - *save_cache_step
      - run:
          name: Publish package
          command: 'pnpm install --frozen-lockfile && pnpm build && npx semantic-release && pnpm update-website'

workflows:
  version: 2
  test-deploy:
    jobs:
      - node-v14
      - node-v16
      - node-v17
      - deploy:
          requires:
            - node-v14
            - node-v16
            - node-v17
          filters:
            branches:
              only: master
